name: Bill Neal Voiceover
favicon: null
layout_spectrum: 0.19204427837394178
typography_spectrum: 0.056479852413758636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9806301177013665
  lightness: 0.9094541985541582
  saturation: 0.45385455316863954
  rhythmicContrast: 0.31142052891664207
purpose: []
